export enum LocationType {
  DINING_TABLE = 'DINING_TABLE',
  HOTEL_ROOM = 'HOTEL_ROOM',
  LOUNGE_SEAT = 'LOUNGE_SEAT',
  HOSPITAL_BED = 'HOSPITAL_BED',
  MEETING_ROOM = 'MEETING_ROOM',
  POOLSIDE = 'POOLSIDE',
}
