export enum ServiceType {
  FOOD_AND_BEVERAGE = 'FOOD_AND_BEVERAGE',
  HOUSEKEEPING = 'HOUSEKEEPING',
  WAITER_CALL = 'WAITER_CALL',
  MAINTENANCE = 'MAINTENANCE',
  AMENITY_REQUEST = 'AMENITY_REQUEST',
  CUSTOM = 'CUSTOM',
}
